# Generated by Django 5.2.5 on 2025-10-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0012_remove_workoutdaycompletion_assignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("video_links", models.JSONField(default=list)),
                ("duration", models.IntegerField(default=30)),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutDayCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("xp_earned", models.IntegerField(default=0)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workoutday",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "workout_day")},
            },
        ),
        migrations.AddField(
            model_name="workoutday",
            name="completed_by",
            field=models.ManyToManyField(
                related_name="completed_days",
                through="workout.WorkoutDayCompletion",
                to="users.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "level_access",
                    models.CharField(default="all", max_length=50),
                ),
                (
                    "difficulty_level",
                    models.CharField(default="easy", max_length=50),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Total duration in days"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        limit_choices_to={"role": "coach"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workoutday",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="workout.workoutprogram",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="users.userprofile",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workoutprogram",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="workoutday",
            unique_together={("program", "day_number")},
        ),
    ]
