# Generated by Django 5.2.5 on 2025-10-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_userprofile_role"),
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutassignment",
            name="program",
            field=models.ForeignKey(
                db_column="program_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="workout.workoutprogram",
            ),
        ),
        migrations.AlterField(
            model_name="workoutassignment",
            name="user_profile",
            field=models.ForeignKey(
                db_column="user_profile_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="workoutday",
            name="program",
            field=models.ForeignKey(
                db_column="program_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="workout.workoutprogram",
            ),
        ),
        migrations.AlterField(
            model_name="workoutdaycompletion",
            name="user_profile",
            field=models.ForeignKey(
                db_column="user_profile_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="workoutdaycompletion",
            name="workout_day",
            field=models.ForeignKey(
                db_column="workout_day_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="workout.workoutday",
            ),
        ),
        migrations.AlterField(
            model_name="workoutprogram",
            name="coach",
            field=models.ForeignKey(
                db_column="coach_id",
                limit_choices_to={"role": "coach"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="users.userprofile",
            ),
        ),
    ]
