# Generated by Django 5.2.5 on 2025-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0002_alter_workoutassignment_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutprogram",
            name="category",
            field=models.CharField(
                choices=[
                    ("strength_training", "Strength Training"),
                    ("cardio", "Cardio"),
                    ("weight_loss", "Weight Loss"),
                    ("muscle_building", "Muscle Building"),
                    ("endurance", "Endurance"),
                    ("flexibility", "Flexibility"),
                    ("full_body", "Full Body"),
                ],
                default="full_body",
                max_length=50,
            ),
        ),
    ]
