# Generated by Django 5.2.5 on 2025-10-11 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0003_workoutprogram_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkoutAssignment",
        ),
    ]
