# Generated by Django 5.2.5 on 2025-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0005_workoutassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutday",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("strength_training", "Strength Training"),
                    ("cardio", "Cardio"),
                    ("hiit", "HIIT"),
                    ("flexibility", "Flexibility"),
                    ("recovery", "Recovery"),
                    ("full_body", "Full Body"),
                    ("upper_body", "Upper Body"),
                    ("lower_body", "Lower Body"),
                    ("core", "Core"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workoutprogram",
            name="difficulty_level",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=50,
            ),
        ),
    ]
