# Generated by Django 5.2.5 on 2025-11-05 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0006_workoutday_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workoutday",
            unique_together=set(),
        ),
    ]
