# Generated by Django 5.2.5 on 2025-11-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0007_alter_workoutday_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("paused", "Paused"),
                    ("overdue", "Overdue"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
    ]
