# Generated by Django 5.2.5 on 2025-11-08 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('user', 'User'), ('coach_certification', 'Coach Certification')], max_length=30)),
                ('content_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('delete_post', 'Delete Post'), ('delete_user', 'Delete User Account'), ('delete_recipe', 'Delete Recipe'), ('approve_certification', 'Approve Coach Certification'), ('reject_certification', 'Reject Coach Certification')], max_length=30)),
                ('reason', models.TextField()),
                ('moderated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='moderation.admin')),
            ],
        ),
    ]
