# Generated by Django 5.2.5 on 2025-11-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_adminmoderation_coach_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminModeration',
        ),
    ]
