# Generated by Django 5.2.6 on 2025-10-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='coach',
        ),
        migrations.CreateModel(
            name='CoachMemberRelationship',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='coach.coach')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='member.member')),
            ],
        ),
    ]
