# Generated by Django 5.2.5 on 2025-10-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0002_remove_member_coach_coachmemberrelationship"),
        ("users", "0015_fitnessgoal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="goals",
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
    ]
