# Generated by Django 5.2.5 on 2025-10-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_remove_member_goals_alter_member_user"),
        ("users", "0015_fitnessgoal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_profile",
                to="users.userprofile",
            ),
        ),
    ]
