# Generated by Django 5.2.5 on 2025-10-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0005_remove_coachmemberrelationship_relationship_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachmemberrelationship",
            name="id",
        ),
        migrations.AddField(
            model_name="coachmemberrelationship",
            name="relationship_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
