# Generated by Django 5.2.5 on 2025-10-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_coachmemberrelationship_id_and_more'),
        ('users', '0015_fitnessgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_post_comments', to='users.userprofile')),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='member.foodpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
