# Generated by Django 5.2.5 on 2025-10-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_foodpostcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodpostcomment',
            old_name='coach',
            new_name='author',
        ),
    ]
