# Generated by Django 5.2.5 on 2025-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessgoal",
            name="goal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lose_weight", "Lose Weight"),
                    ("build_muscle", "Build Muscle"),
                    ("improve_endurance", "Improve Endurance"),
                    ("general_fitness", "General Fitness"),
                    ("increase_flexibility", "Increase Flexibility"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
