# Generated by Django 5.2.5 on 2025-10-02 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0012_remove_workoutdaycompletion_assignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "coach_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "certification_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coach_certifications/",
                    ),
                ),
                (
                    "status_approval",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
