# Generated by Django 5.2.5 on 2025-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="public_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
