# Generated by Django 5.2.5 on 2025-10-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0014_delete_foodpost"),
        ("workout", "0004_delete_workoutassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        db_column="program_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workoutprogram",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        db_column="user_profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_date"],
            },
        ),
    ]
