# Generated by Django 5.2.5 on 2025-11-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_alter_reciperating_rating"),
        ("users", "0016_remove_userachievement_achievement_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reciperating",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reciperating",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user_profile"), name="one_rating_per_user"
            ),
        ),
    ]
