# Generated by Django 5.2.5 on 2025-10-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_reciperating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='access_level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='silver', max_length=50),
        ),
    ]
