# Generated by Django 5.2.5 on 2025-08-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_role_selected',
            field=models.BooleanField(default=False),
        ),
    ]
