# Generated by Django 5.2.5 on 2025-09-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('coach', 'Coach'), ('member', 'Member'), ('admin', 'Administrator')], default='normal', max_length=10),
        ),
    ]
