# Generated by Django 5.2.5 on 2025-09-27 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0007_achievement_foodpost_userachievement_userlevel_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="name",
            new_name="title",
        ),
    ]
