# Generated by Django 5.2.5 on 2025-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
