# Generated by Django 5.2.6 on 2025-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_coach_full_name_coach_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
