# Generated by Django 5.2.5 on 2025-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_name_achievement_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TH", "Thailand"),
                    ("USA", "United States"),
                    ("UK", "United Kingdom"),
                    ("JP", "Japan"),
                    ("LA", "Laos"),
                    ("KR", "South Korea"),
                    ("O", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
