# Generated by Django 5.2.5 on 2025-09-29 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_userprofile_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlevel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userlevel",
            name="updated_at",
        ),
    ]
