# Generated by Django 5.2.6 on 2025-09-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_coach_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='phone_number',
        ),
    ]
