# Generated by Django 5.2.5 on 2025-09-30 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_userlevel_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FitnessGoal",
        ),
    ]
