# Generated by Django 5.2.5 on 2025-10-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_delete_fitnessgoal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutdaycompletion",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="workoutdaycompletion",
            name="user_profile",
        ),
        migrations.RemoveField(
            model_name="workoutprogram",
            name="coach",
        ),
        migrations.DeleteModel(
            name="WorkoutAssignment",
        ),
        migrations.DeleteModel(
            name="WorkoutDayCompletion",
        ),
        migrations.DeleteModel(
            name="WorkoutProgram",
        ),
    ]
