# Generated by Django 5.2.5 on 2025-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_workoutdaycompletion_assignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("normal", "Normal User"),
                    ("coach", "Coach"),
                    ("member", "Member"),
                    ("admin", "Administrator"),
                ],
                max_length=10,
            ),
        ),
    ]
