# Generated by Django 5.2.5 on 2025-10-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_userprofile_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FoodPost",
        ),
    ]
