# Generated by Django 5.2.5 on 2025-10-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_workoutdaycompletion_assignment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_streak_date",
        ),
    ]
