# Generated by Django 5.2.5 on 2025-10-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_delete_foodpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lose_weight", "Lose Weight"),
                            ("build_muscle", "Build Muscle"),
                            ("improve_endurance", "Improve Endurance"),
                            ("general_fitness", "General Fitness"),
                            ("increase_flexibility", "Increase Flexibility"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitness_goals",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
