# Generated by Django 5.2.5 on 2025-11-11 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_fitnessgoal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userachievement",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="user_profile",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="UserAchievement",
        ),
    ]
