name: Lint with Flake8

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 backend --statistics --count --max-line-length=88 --filename=*.py